= Pipeline setup script
Simon Walker <s.r.walker101@googlemail.com>

This script installs the whole pipeline, into the current repository.

*To install the pipeline into the current directory, run the `setup.py` script. This downloads everything and compiles all required programs.*

Afterwards you need to add to your .bashrc:

[source,sh]
----
# <dir> is the location you installed to
export PATH=${HOME}/anaconda/bin:<dir>/bin:${PATH}
export LD_LIBRARY_PATH=<dir>/lib:${LD_LIBRARY_PATH}
----

You may need to edit the commands in the script if it does not completely work. Hopefully the script has been written in a fairly easy to change style. The actual commands are run with the `sh` function which simply takes a string containing the bash command to run. For example:

[source,python]
----
# CD into casu-lightcurves directory and initialise submodules
with cd('casu-lightcurves'):
    sh('git submodule init')
    sh('git submodule update')
----


== Requirements

The machine you're installing onto only requires the following:

* `git`
* `python`
* `wget`
* `pkg-config`
* `gfortran`
* `g++`

== Development and testing

Included in this repository is a `Vagrantfile` which sets up a debian virtual machine, and provisions the minimal initial requirements listed above.
