---
- hosts: all
  tasks:
  - name: Install required packages
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
    with_items:
    - git
    - python
    - wget
    become: yes

  - name: Ensure .ssh dir exists
    file: path=~/.ssh state=directory

  - name: Ensure pipeline test dir exists
    file: path=/pipeline state=directory owner=vagrant group=vagrant
    become: true
